### ISSUE TITLE
Parameter input tweaks

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/science-gateway-inputs#15]
- [x] Add slider for geometry (linked to vtk component)
- [x] Check mechanism for linking multiple sliders to same vtk component
- [x] Try switch for checkbox (http://coreui.io/docs/new-components/switches)
- [x] Add hyperlink to accordion section titles (it's not obvious where to click at the moment) and animation for accordion expand/collapse

**Comment by myyong** [comment]
What tweaks?

**Comment by myyong** [comment]
Ah, tweak number 1: What picture do you want for representing each job on the dashboard?

**Comment by masonlr** [comment]
- [ ] Add slider for geometry (linked to vtk component)
- [ ] Check mechanism for linking multiple sliders to same vtk component
- [ ] Try switch for checkbox (http://coreui.io/docs/new-components/switches)
- [ ] Add hyperlink to accordion section titles (it's not obvious where to click at the moment) and animation for accordion expand/collapse

**Comment by masonlr** [comment]
Yep good idea, I need to run some 3D product changeover simulations and generate a good screenshot.

**Comment by myyong** [comment]
I like the switches!

**Comment by masonlr** [comment]
Okay, great.

I'll start on the vtk slider for geometry,

**Comment by myyong** [comment]
Keep in mind one of Roma's tips: For use on tablets, we have to make it easy for users with big fingers to select/click components

**Comment by myyong** [comment]
I can try looking at the switches tomorrow.

**Comment by RadkaJersak** [comment]
added switch for checkbox, now working on accordion section titles
