### ISSUE TITLE
sliders don't show properly in firefox (at least on Linux)

### ISSUE THREAD

**Issue by dpshelio** [alan-turing-institute/science-gateway-inputs#28]
Sliders work in the [demo page](http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html) using firefox

**Comment by myyong** [comment]
It works in updated Chrome now 🗡

**Comment by klapaukh** [comment]
I think this is caused by an out dated version of webpack. This seems fixed in the theejs branch (threejs doesn't work with old webpack either).

**Comment by masonlr** [comment]
@klapaukh has this now been merged in master. Can we close this issue?

**Comment by klapaukh** [comment]
More people should check that this is now fixed. Then it can be closed.
