### ISSUE TITLE
forms are not validated

### ISSUE THREAD

**Issue by dpshelio** [alan-turing-institute/science-gateway-inputs#33]
Forms could be validated in the html before saving or submiting the job, this can be done in `<input` with the properties `type='number' min="xx" max="XX" step="Any">`

**Comment by masonlr** [comment]
Yes, this would be great. 

**User story:**
User enters 12 for a text input field (for which `min=1` and `max=10`)

**Behaviour:**
A helper message should be shown below/beside the text input with the text `viscosity must be set to a value between 1 and 10`

**Comment by myyong** [comment]
Done
