### ISSUE TITLE
Middleware connection

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/science-gateway-inputs#8]
- [x] Get data off middleware to create UI
    - [x] Data is here
    - [ ] Full UI creation from data
- [ ] Modify config, send new data off to UI
- [ ] Implement global variable for middleware URL (set to `localhost:5000` or an Azure URL)

**Comment by masonlr** [comment]
Currently, I am building in the connection between the frontend in the branch `8-middleware-connection`. This is a work in progress: (i) middleware testing is being done on `localhost:5000` using the middleware branch `wip-job-action-development`, (ii) middleware commands are being relayed to the Imperial College cx1 cluster itself.

I am doing this to understand and check the behaviour of PBS on the actual targeted cluster. A priority (once these initial tests are working) is to enable Blue jobs to run on the mock Azure cluster VM. This will enable and speed up generic end-to-end testing of the science gateway project.
